/** Random lines shown in voice preview TTS URLs. */
export const VOICE_PREVIEW_LINES = [
  "You must construct additional pylons!",
  "The cake is a lie!",
  "It's dangerous to go alone! Take this.",
  "Do a barrel roll!",
  "War. War never changes.",
  "Would you kindly?",
  "Stay a while and listen.",
  "All your base are belong to us.",
  "It's super effective!",
  "What is a man? A miserable little pile of secrets!",
  "You have died of dysentery.",
  "A man chooses. A slave obeys.",
  "Stop right there, criminal scum!",
  "You were almost a Jill sandwich!",
  "Kept you waiting, huh?",
  "You've met with a terrible fate, haven't you?",
  "Did I ever tell you the definition of insanity?",
  "Time is money, friend!",
  "My life for Aiur!",
  "Let me guess, someone stole your sweetroll?",
  "Look behind you, a three-headed monkey!",
  "How about a round of Gwent?",
  "Another settlement needs your help.",
  "Hey cousin, want to go bowling?",
  "Welcome to the circus of value!",
  "Watch those wrist rockets!",
  "Now you're thinking with portals.",
  "Praise the sun! Jolly cooperation!",
  "Not even death can save you from me.",
  "Zug zug! Whatcha want me to do?",
  "Finish him! Fatality!",
  "Hey! Listen! Hey! Watch out!",
  "Boy! Come here, boy. We have work to do.",
  "Let's a-go! Wahoo! Here we go!",
  "Snake? Snake! Snaaake!",
  "Booker, catch! Heads or tails?",
  "Job's done. Off I go then. More work?",
];
