/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-alt": "var(--color-surface-alt)",
        "app-border": "var(--color-border)",
        "border-subtle": "var(--color-border-subtle)",
        "text-primary": "var(--color-text)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-faint": "var(--color-text-faint)",
        "input-bg": "var(--color-input-bg)",
        "input-border": "var(--color-input-border)",
        card: "var(--color-card)",
        overlay: "var(--color-overlay)",
        active: "var(--color-active)",
        "code-bg": "var(--color-code-bg)",
        "code-border": "var(--color-code-border)",
        accent: "var(--color-accent)",
        "accent-light": "var(--color-accent-light)",
        "accent-surface": "var(--color-accent-surface)",
        "accent-border": "var(--color-accent-border)",
        success: "var(--color-success)",
        "success-surface": "var(--color-success-surface)",
        warning: "var(--color-warning)",
        "warning-surface": "var(--color-warning-surface)",
        error: "var(--color-error)",
        "error-surface": "var(--color-error-surface)",
        "user-bubble": "var(--color-user-bubble)",
      },
    },
  },
  plugins: [],
};
