/**
 * Generates a hash of the GraphQL schema file and writes it to a
 * TypeScript module that the Apollo client imports for cache versioning.
 *
 * Run automatically after codegen via the `codegen` npm script.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(__dirname, "../../server/schema.graphql");
const outPath = resolve(__dirname, "../src/graphql/generated/schemaHash.ts");

const schema = readFileSync(schemaPath, "utf-8");
const hash = createHash("sha256").update(schema).digest("hex").slice(0, 12);

writeFileSync(
  outPath,
  `/* eslint-disable */\n// Auto-generated by scripts/generateSchemaHash.mjs — do not edit.\nexport const SCHEMA_HASH = "${hash}";\n`,
);

console.log(`Schema hash: ${hash}`);
